import = [
    "$HOME/.config/alacritty/themes/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.999 # workaround for macos stutter

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
