[tools]
terraform = "latest"
packer = "latest"
jq = "latest"
go = "latest"
java = "latest"
task = "latest"
k9s = "latest"
python = "latest"
shellcheck = "latest"
lazygit = "latest"
node = "lts"

[env]
